/* ICON URLs */
const ICONS = {
    metro: "https://stolica.bg/svg/01-metro.svg",
    tram: "https://stolica.bg/svg/02-tram.svg",
    trolley: "https://stolica.bg/svg/04-trolley.svg",
    bus: "https://stolica.bg/svg/05-bus.svg",
    nightbus: "https://stolica.bg/svg/07-night-bus.svg"
};

/* COLOR MAP */
const COLORS = {
    metro1: "#ec2029",
    metro2: "#1077bc",
    metro3: "#3bb44b",
    metro4: "#fcd403",
    tram: "#f6921e",
    trolley: "#0095da",
    bus: "#be1e2d",
    nightbus: "#000000"
};

/* LINE DATA */
const lines = {
    "bus-1": {
        number: "1",
        type: "bus",
        directions: [
            {
                name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ",
                stops: [
                    { name: "СЕЛО КОКАЛЯНЕ", onDemand: false },
                    { name: "УЛ. ЦАР ИВАН АСЕН ІІ", onDemand: false },
                    { name: "УЛ. ЦАР ИВАН ШИШМАН", onDemand: false },
                    { name: "УЛ. ЛАТИНКА", onDemand: false },
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: true },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "СБА", onDemand: true },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "ТРИЪГЪЛНИКА КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "КОМПЛЕКС ЦАРИГРАДСКИ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "ХЕРМЕС ПАРК", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "СОФИЯ ТЕХ ПАРК", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                ]
            },
            {
                name: "КОКАЛЯНЕ",
                stops: [
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "ТРИЪГЪЛНИКА КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "СБА", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "УЛ. ЛАТИНКА", onDemand: false },
                    { name: "УЛ. ЦАР ИВАН ШИШМАН", onDemand: false },
                    { name: "УЛ. ЦАР ИВАН АСЕН ІІ", onDemand: false },
                    { name: "СЕЛО КОКАЛЯНЕ", onDemand: false }
                ]
            }
        ]
    },
	
"bus-У1": {
        number: "У1",
        type: "bus",
        directions: [
            {
                name: "32 СУ СВ. КЛИМЕНТ ОХРИДСКИ",
                stops: [
                    { name: "БАЛКАНКАР АД", onDemand: false },
                    { name: "Ж.К. КРАСНА ПОЛЯНА", onDemand: false },
                    { name: "УЛ. ДОБРОТИЧ", onDemand: false },
                    { name: "БУЛ. ВАРДАР", onDemand: false },
                    { name: "БУЛ. АЛ. СТАМБОЛИЙСКИ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ВАРДАР", onDemand: false },
                    { name: "УЛ. ХАЙДУТ СИДЕР", onDemand: false },
                    { name: "УЛ. ХАЙДУТ СИДЕР", onDemand: false },
                    { name: "УЛ. ЗОГРАФСКИ МАНАСТИР", onDemand: false },
                    { name: "УЛ. ЦАР СИМЕОН", onDemand: false },
                    { name: "УЛ. ДИМИТЪР ПЕТКОВ", onDemand: false },
                    { name: "УЛ. ОДРИН", onDemand: false },
                    { name: "134 СУ ДИМЧО ДЕБЕЛЯНОВ", onDemand: false },
                    { name: "18 СУ УИЛЯМ ГЛАДСТОН", onDemand: false },
                    { name: "32 СУ СВ. КЛИМЕНТ ОХРИДСКИ", onDemand: false },
                ]
            },
            {
                name: "",
                stops: [
                    
                ]
            }
        ]
    },

	"bus-У2": {
        number: "У2",
        type: "bus",
        directions: [
            {
                name: "18 СУ УИЛЯМ ГЛАДСТОН",
                stops: [
                    { name: "Ж.К. ЛЮЛИН 5", onDemand: false },
                    { name: "УЛ. ПОРУЧИК ГР. ЗАГОРСКИ", onDemand: false },
                    { name: "УЛ. КАП. ВАСИЛ ДАНАДЖИЕВ", onDemand: false },
                    { name: "МАГАЗИН ВИТОША", onDemand: false },
                    { name: "ОБЩИНА ЛЮЛИН", onDemand: false },
                    { name: "ТЪРГОВСКИ ЦЕНТЪР ЛЮЛИН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЛЮЛИН", onDemand: false },
                    { name: "УЛ. ЛУИ ПАСТЬОР", onDemand: false },
                    { name: "БУЛ. ЦАРИЦА ЙОАНА", onDemand: false },
                    { name: "УЛ. ГОЦЕ ДЕЛЧЕВ", onDemand: false },
                    { name: "БЛ. 135 Ж.К. ЛЮЛИН 10", onDemand: false },
                    { name: "УЛ. ОРИОН", onDemand: false },
                    { name: "ЗАПАДЕН ПАРК", onDemand: false },
                    { name: "УЛ. ОРЯХОВО", onDemand: false },
                    { name: "УЛ. ПЛОВДИВ", onDemand: false },
					{ name: "НАДЛЕЗ НАДЕЖДА", onDemand: false },
					{ name: "БУЛ. ГЕН. Н. СТОЛЕТОВ", onDemand: false },
					{ name: "ПЕТА ГРАДСКА БОЛНИЦА", onDemand: false },
					{ name: "БУЛ. КНЯГИНЯ МАРИЯ ЛУИЗА", onDemand: false },
					{ name: "УЛ. ОХРИД", onDemand: false },
					{ name: "УЛ. ОПЪЛЧЕНСКА", onDemand: false },
					{ name: "46-ТО ОУ КОНСТАНТИН ФОТИНОВ", onDemand: false },
					{ name: "32 СУ СВ. КЛИМЕНТ ОХРИДСКИ", onDemand: false },
					{ name: "18 СУ УИЛЯМ ГЛАДСТОН", onDemand: false },
                ]
            },
            {
                name: "",
                stops: [
                    
                ]
            }
        ]
    },
	
    "bus-3": {
        number: "3",
        type: "bus",
        directions: [
            {
                name: "УЛ. ГЕН. ГУРКО",
                stops: [
                    { name: "СЕЛО ДОЛНИ ПАСАРЕЛ", onDemand: false },
                    { name: "МОСТА ДОЛНИ ПАСАРЕЛ", onDemand: false },
                    { name: "ВЕЦ ПАСАРЕЛ", onDemand: true },
                    { name: "ЯЗ. ПАСАРЕЛ", onDemand: true },
                    { name: "БАРАЖА ЯЗ. ПАСАРЕЛ", onDemand: true },
                    { name: "РЕСТОРАНТ ЗЛАТНАТА РИБКА", onDemand: true },
                    { name: "ЗАСЛОН СИНАНИЦА", onDemand: false },
                    { name: "МАНАСТИР СВ. НИКОЛА", onDemand: true },
                    { name: "ДЯВОЛСКИ МОСТ", onDemand: true },
                    { name: "В.З. КИТКАТА", onDemand: true },
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: true },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "СБА", onDemand: true },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "ТРИЪГЪЛНИКА КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "КОМПЛЕКС ЦАРИГРАДСКИ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "ХЕРМЕС ПАРК", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "ХОТЕЛ ПЛИСКА", onDemand: false },
                    { name: "ПЛ. ОРЛОВ МОСТ", onDemand: false },
                    { name: "УЛ. ГЕНЕРАЛ ГУРКО", onDemand: false },
                ]
            },
            {
                name: "ДОЛНИ ПАСАРЕЛ",
                stops: [
                    { name: "УЛ. ГЕНЕРАЛ ГУРКО", onDemand: false },
                    { name: "ПЛ. ОРЛОВ МОСТ", onDemand: false },
                    { name: "ХОТЕЛ ПЛИСКА", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "ТРИЪГЪЛНИКА КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "СБА", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: true },
                    { name: "В.З. КИТКАТА", onDemand: true },
                    { name: "ДЯВОЛСКИ МОСТ", onDemand: true },
                    { name: "МАНАСТИР СВ. НИКОЛА", onDemand: true },
                    { name: "ЗАСЛОН СИНАНИЦА", onDemand: false },
                    { name: "РЕСТОРАНТ ЗЛАТНАТА РИБКА", onDemand: true },
                    { name: "БАРАЖА ЯЗ. ПАСАРЕЛ", onDemand: true },
                    { name: "ЯЗ. ПАСАРЕЛ", onDemand: true },
                    { name: "ВЕЦ ПАСАРЕЛ", onDemand: true },
                    { name: "МОСТА ДОЛНИ ПАСАРЕЛ", onDemand: false },
                    { name: "СЕЛО ДОЛНИ ПАСАРЕЛ", onDemand: false }
                ]
            }
        ]
    },
    "bus-4": {
        number: "4",
        type: "bus",
        directions: [
            {
                name: "МЛАДОСТ 1",
                stops: [
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "СБА", onDemand: true },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "САМОКОВСКО ШОСЕ", onDemand: false },
                    { name: "БЛ. 1 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "БЛ. 43 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "БЛ. 39 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "КУЛИНАРЕН КОМБИНАТ ПЕЙФИЛ", onDemand: false },
                    { name: "ВИК ЕАД - СОФИЯ", onDemand: false },
                    { name: "Ж.К. МЛАДОСТ 3", onDemand: false },
                    { name: "ОБЩИНА МЛАДОСТ", onDemand: false },
                    { name: "БЛ. 327 Ж.К. МЛАДОСТ 3", onDemand: false },
                    { name: "БЛ. 205 Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "БЛ. 206 Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "БЛ. 245 Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "Ж.К. МЛАДОСТ 1", onDemand: false },
                ]
            },
            {
                name: "КОКАЛЯНСКО ХАНЧЕ",
                stops: [
                    { name: "Ж.К. МЛАДОСТ 1", onDemand: false },
                    { name: "ПОСОЛСТВАТА", onDemand: false },
                    { name: "ОНКОЛОГИЧЕН ДИСПАНСЕР", onDemand: false },
                    { name: "ПАЗАРА МЛАДОСТ 1", onDemand: false },
                    { name: "БЛ. 66 Ж.К. МЛАДОСТ 1", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ АЛ. МАЛИНОВ", onDemand: false },
                    { name: "БЛ. 69 Ж.К. МЛАДОСТ 1", onDemand: false },
                    { name: "БЛ. 245 Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "БЛ. 206 Ж.К. МЛАДОСТ 2", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ АКАД. А.Т.-БАЛАН", onDemand: false },
                    { name: "БЛ. 327 Ж.К. МЛАДОСТ 3", onDemand: false },
                    { name: "ОБЩИНА МЛАДОСТ", onDemand: false },
                    { name: "Ж.К. МЛАДОСТ 3", onDemand: false },
                    { name: "ВИК ЕАД - СОФИЯ", onDemand: false },
                    { name: "КУЛИНАРЕН КОМБИНАТ ПЕЙФИЛ", onDemand: false },
                    { name: "УЛ. ИНЖ. ГЕОРГИ БЕЛОВ", onDemand: false },
                    { name: "БЛ. 39 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "БЛ. 43 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "БЛ. 1 Ж.К. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "САМОКОВСКО ШОСЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "СБА", onDemand: true },
                    { name: "ДЕТСКО ГРАДЧЕ", onDemand: true },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: true },
                    { name: "БАНЯТА ПАНЧАРЕВО", onDemand: true },
                    { name: "ГРЕБНА БАЗА", onDemand: true },
                    { name: "КВ. ПАНЧАРЕВО", onDemand: true },
                    { name: "ПЛАЖА ПАНЧАРЕВО", onDemand: true },
                    { name: "КОКАЛЯНСКО ХАНЧЕ", onDemand: false },
                ]
            }
        ]
    },
    "bus-5": {
        number: "5",
        type: "bus",
        directions: [
            {
                name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ",
                stops: [
                    { name: "СЕЛО ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. ВАСИЛ ЛЕВСКИ", onDemand: false },
                    { name: "ЦЕНТЪР ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "КМЕТСТВО ЛОЗЕН", onDemand: false },
                    { name: "СЕЛО ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. РАЛИЦА", onDemand: false },
                    { name: "УЛ. СИНЧЕЦ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "АВТОРЕМОНТНА БАЗА", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "КОРАБЧЕТО", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "ХЕРМЕС ПАРК", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "СОФИЯ ТЕХ ПАРК", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                ]
            },
            {
                name: "ДОЛНИ ЛОЗЕН",
                stops: [
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОРАБЧЕТО", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "АВТОРЕМОНТНА БАЗА", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. СИНЧЕЦ", onDemand: false },
                    { name: "УЛ. РАЛИЦА", onDemand: false },
                    { name: "СЕЛО ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "КМЕТСТВО ЛОЗЕН", onDemand: false },
                    { name: "ЦЕНТЪР ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. ВАСИЛ ЛЕВСКИ", onDemand: false },
                    { name: "СЕЛО ДОЛНИ ЛОЗЕН", onDemand: false },
                ]
            }
        ]
    },
    "bus-6": {
        number: "6",
        type: "bus",
        directions: [
            {
                name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ",
                stops: [
                    { name: "СЕЛО ГЕРМАН", onDemand: false },
                    { name: "86-ТИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "СТАДИОНА ГЕРМАН", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "В.З. ГЕРМАН", onDemand: false },
                    { name: "КОРИЯТА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "КОРАБЧЕТО", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "ХЕРМЕС ПАРК", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "СОФИЯ ТЕХ ПАРК", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                ]
            },
            {
                name: "ГЕРМАН",
                stops: [
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "СК ЦСКА", onDemand: false },
                    { name: "СПОРТНА ЗАЛА АРЕНА АРМЕЕЦ", onDemand: false },
                    { name: "ПЛОЩАД НА АВИАЦИЯТА", onDemand: false },
                    { name: "УМБАЛ СВ. АННА", onDemand: false },
                    { name: "ДЪРЖАВНА ПЕЧАТНИЦА", onDemand: false },
                    { name: "КОМПЛЕКС НА БАН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЦАРИГРАДСКО ШОСЕ", onDemand: false },
                    { name: "КОРАБЧЕТО", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "КОРИЯТА", onDemand: false },
                    { name: "В.З. ГЕРМАН", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "СТАДИОНА ГЕРМАН", onDemand: false },
                    { name: "86-ТИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "СЕЛО ГЕРМАН", onDemand: false },
                ]
            }
        ]
    },
    "bus-7": {
        number: "7",
        type: "bus",
        directions: [
            {
                name: "ГАРА ИСКЪР",
                stops: [
                    { name: "ЖП ГАРА ВЕРИЛА", onDemand: false },
                    { name: "МАНАСТИР СВ. АПОСТОЛИ ПЕТЪР И ПАВЕЛ", onDemand: false },
                    { name: "СТРАННОПРИЕМНИЦАТА", onDemand: false },
                    { name: "НАЧАЛО С. ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "ЦЕНТЪР ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "КМЕТСТВО ЛОЗЕН", onDemand: false },
                    { name: "СЕЛО ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. РАЛИЦА", onDemand: false },
                    { name: "УЛ. СИНЧЕЦ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "АВТОРЕМОНТНА БАЗА", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "БЛ. 501 Ж.К. ДРУЖБА 2", onDemand: false },
                    { name: "РАЗКЛОНА ЗА АП ДРУЖБА", onDemand: false },
                    { name: "ТЕЦ ИЗТОК", onDemand: false },
                    { name: "ДЕПО ИСКЪР", onDemand: false },
                    { name: "СОФИЯ МЕД АД", onDemand: false },
                    { name: "КВ. ГАРА ИСКЪР", onDemand: false },
                    { name: "ГАРА ИСКЪР", onDemand: false },
                ]
            },
            {
                name: "ГАРА ВЕРИЛА",
                stops: [
                    { name: "ГАРА ИСКЪР", onDemand: false },
                    { name: "КВ. ГАРА ИСКЪР", onDemand: false },
                    { name: "СОФИЯ МЕД АД", onDemand: false },
                    { name: "ДЕПО ИСКЪР", onDemand: false },
                    { name: "ТЕЦ ИЗТОК", onDemand: false },
                    { name: "РАЗКЛОНА ЗА АП ДРУЖБА", onDemand: false },
                    { name: "БЛ. 501 Ж.К. ДРУЖБА 2", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "МОСТА ЗА РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "РЕЗИДЕНЦИЯ ВРАНА", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "АВТОРЕМОНТНА БАЗА", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "УЛ. СИНЧЕЦ", onDemand: false },
                    { name: "УЛ. РАЛИЦА", onDemand: false },
                    { name: "СЕЛО ГОРНИ ЛОЗЕН", onDemand: false },
                    { name: "КМЕТСТВО ЛОЗЕН", onDemand: false },
                    { name: "ЦЕНТЪР ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "НАЧАЛО С. ДОЛНИ ЛОЗЕН", onDemand: false },
                    { name: "СТРАННОПРИЕМНИЦАТА", onDemand: false },
                    { name: "МАНАСТИР СВ. АПОСТОЛИ ПЕТЪР И ПАВЕЛ", onDemand: false },
                    { name: "ЖП ГАРА ВЕРИЛА", onDemand: false },
                ]
            }
        ]
    },
    "bus-8": {
        number: "8",
        type: "bus",
        directions: [
            {
                name: "КРИВИНА",
                stops: [
                    { name: "СЕЛО ГЕРМАН", onDemand: false },
                    { name: "86-ТИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "СТАДИОНА ГЕРМАН", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "БЛ. 501 Ж.К. ДРУЖБА 2", onDemand: false },
                    { name: "РАЗКЛОНА ЗА АП ДРУЖБА", onDemand: false },
                    { name: "ТЕЦ ИЗТОК", onDemand: false },
                    { name: "ДЕПО ИСКЪР", onDemand: false },
                    { name: "СОФИЯ МЕД АД", onDemand: false },
                    { name: "КВ. ГАРА ИСКЪР", onDemand: false },
                    { name: "ГАРА ИСКЪР", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "ТРЪНСКА МАХАЛА", onDemand: false },
                    { name: "ДЕТСКИ ДОМ", onDemand: false },
                    { name: "КВ. БУСМАНЦИ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА БУСМАНЦИ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА КАЗИЧЕНЕ", onDemand: false },
                    { name: "БЕТОНОВ ВЪЗЕЛ КАЗИЧЕНЕ", onDemand: false },
                    { name: "СТАДИОНА КАЗИЧЕНЕ", onDemand: false },
                    { name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
                    { name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
                    { name: "КВ. ВИДНИТЕ", onDemand: false },
                    { name: "РАЗКЛОН ЗА КВ. ВИДНИТЕ", onDemand: false },
                    { name: "ЕЗЕРОТО С. КАЗИЧЕНЕ", onDemand: false },
                    { name: "ЦЕНТЪР КВ. ВИДНИТЕ", onDemand: false },
                    { name: "ЕЗЕРОТО С. КАЗИЧЕНЕ", onDemand: false },
                    { name: "ГАРА КАЗИЧЕНЕ", onDemand: false },
                    { name: "УЛ. ЦАР БОРИС ІІІ", onDemand: false },
                    { name: "УЛ. ДИМИТЪР АШОВ", onDemand: false },
                    { name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
                    { name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
                    { name: "РИТЕКС АД", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА КРИВИНА", onDemand: false },
                    { name: "ПАРКА С. КРИВИНА", onDemand: false },
                    { name: "УЛ. ЛЮЛЯК", onDemand: false },
                    { name: "ЦЕНТЪРА С. КРИВИНА", onDemand: false },
                    { name: "СЕЛО КРИВИНА", onDemand: false },
                ]
            },
            {
                name: "ГЕРМАН",
                stops: [
                    { name: "СЕЛО КРИВИНА", onDemand: false },
                    { name: "ЦЕНТЪРА С. КРИВИНА", onDemand: false },
                    { name: "УЛ. ЛЮЛЯК", onDemand: false },
                    { name: "ПАРКА С. КРИВИНА", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА КРИВИНА", onDemand: false },
                    { name: "РИТЕКС АД", onDemand: false },
                    { name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
                    { name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
                    { name: "УЛ. ДИМИТЪР АШОВ", onDemand: false },
                    { name: "УЛ. ЦАР БОРИС ІІІ", onDemand: false },
                    { name: "ГАРА КАЗИЧЕНЕ", onDemand: false },
                    { name: "ЕЗЕРОТО С. КАЗИЧЕНЕ", onDemand: false },
                    { name: "ЦЕНТЪР КВ. ВИДНИТЕ", onDemand: false },
                    { name: "ЕЗЕРОТО С. КАЗИЧЕНЕ", onDemand: false },
                    { name: "РАЗКЛОН ЗА КВ. ВИДНИТЕ", onDemand: false },
                    { name: "КВ. ВИДНИТЕ", onDemand: false },
                    { name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
                    { name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
                    { name: "СТАДИОНА КАЗИЧЕНЕ", onDemand: false },
                    { name: "БЕТОНОВ ВЪЗЕЛ КАЗИЧЕНЕ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА КАЗИЧЕНЕ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА БУСМАНЦИ", onDemand: false },
                    { name: "КВ. БУСМАНЦИ", onDemand: false },
                    { name: "ДЕТСКИ ДОМ", onDemand: false },
                    { name: "ТРЪНСКА МАХАЛА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "ГАРА ИСКЪР", onDemand: false },
                    { name: "КВ. ГАРА ИСКЪР", onDemand: false },
                    { name: "СОФИЯ МЕД АД", onDemand: false },
                    { name: "ДЕПО ИСКЪР", onDemand: false },
                    { name: "ТЕЦ ИЗТОК", onDemand: false },
                    { name: "РАЗКЛОНА ЗА АП ДРУЖБА", onDemand: false },
                    { name: "БЛ. 501 Ж.К. ДРУЖБА 2", onDemand: false },
                    { name: "ГОРУБЛЯНСКО ХАНЧЕ", onDemand: false },
                    { name: "УЛ. ЦВЕТНА ГРАДИНА", onDemand: false },
                    { name: "КВ. ГОРУБЛЯНЕ", onDemand: false },
                    { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ГЕРМАН", onDemand: false },
                    { name: "СТАДИОНА ГЕРМАН", onDemand: false },
                    { name: "86-ТИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "СЕЛО ГЕРМАН", onDemand: false },
                ]
            }
        ]
    },
    "bus-8TM": {
        number: "8TM",
        type: "bus",
        directions: [
            {
                name: "ЛЮЛИН 5",
                stops: [
                    { name: "УЛ. ТЪРНОВО", onDemand: false },
                    { name: "УЛ. ГЕН. АСЕН НИКОЛОВ", onDemand: false },
                    { name: "УЛ. ГЕН. НИКОЛА ГЕНЕВ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЛЮЛИН", onDemand: false },
                    { name: "ТЪРГОВСКИ ЦЕНТЪР ЛЮЛИН", onDemand: false },
                    { name: "ОБЩИНА ЛЮЛИН", onDemand: false },
                    { name: "МАГАЗИН ВИТОША", onDemand: false },
                    { name: "БУЛ. Д-Р ПЕТЪР ДЕРТЛИЕВ", onDemand: false },
                    { name: "БУЛ. ПЕТЪР ДЕРТЛИЕВ", onDemand: false },
                    { name: "БЛ. 539 Ж.К. ЛЮЛИН 5", onDemand: false },
                    { name: "Ж.К. ЛЮЛИН 5", onDemand: false },
                ]
            },
            {
                name: "УЛ. ТЪРНОВО (ЛЮЛИН 8)",
                stops: [
                    { name: "Ж.К. ЛЮЛИН 5", onDemand: false },
                    { name: "БЛ. 539 Ж.К. ЛЮЛИН 5", onDemand: false },
                    { name: "БУЛ. Д-Р ПЕТЪР ДЕРТЛИЕВ", onDemand: false },
                    { name: "МАГАЗИН ВИТОША", onDemand: false },
                    { name: "ОБЩИНА ЛЮЛИН", onDemand: false },
                    { name: "ТЪРГОВСКИ ЦЕНТЪР ЛЮЛИН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ЛЮЛИН", onDemand: false },
                    { name: "УЛ. ГЕН. НИКОЛА ГЕНЕВ", onDemand: false },
                    { name: "УЛ. ГЕН. АСЕН НИКОЛОВ", onDemand: false },
                    { name: "Ж.К. ЛЮЛИН 8", onDemand: false },
                ]
            }
        ]
    },
    "bus-9": {
        number: "9",
        type: "bus",
        directions: [
            {
                name: "УЛ. ГЕН. ГУРКО",
                stops: [
                    { name: "АВТОБАЗА ИСКЪР", onDemand: false },
                    { name: "БКС СРЕДЕЦ", onDemand: false },
                    { name: "СЛАТИНА БУЛГАРПЛОД", onDemand: false },
                    { name: "ВТУ Т. КАБЛЕШКОВ", onDemand: false },
                    { name: "Ж.К. СЛАТИНА", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "НУ ЗА ТАНЦОВО ИЗКУСТВО", onDemand: false },
                    { name: "УЛ. НИКОЛАЙ КОПЕРНИК", onDemand: false },
                    { name: "УЛ. АЛЕКСАНДЪР ЖЕНДОВ", onDemand: false },
                    { name: "УЛ. ХЕМУС", onDemand: false },
                    { name: "РУМЪНСКО ПОСОЛСТВО", onDemand: false },
                    { name: "31-ВО СУЧЕМ", onDemand: false },
                    { name: "УЛ. КАЛИМАНЦИ", onDemand: false },
                    { name: "УЛ. ОБОРИЩЕ", onDemand: false },
                    { name: "УЛ. ЧЕРКОВНА", onDemand: false },
                    { name: "129-ТО ОУ", onDemand: false },
                    { name: "ВОЕННА АКАДЕМИЯ", onDemand: false },
                    { name: "ПЛ. ОРЛОВ МОСТ", onDemand: false },
                    { name: "УЛ. ГЕНЕРАЛ ГУРКО", onDemand: false },
                ]
            },
            {
                name: "АВТОБАЗА ИСКЪР",
                stops: [
                    { name: "УЛ. ГЕНЕРАЛ ГУРКО", onDemand: false },
                    { name: "СУ СВ. КЛИМЕНТ ОХРИДСКИ", onDemand: false },
                    { name: "ВОЕННА АКАДЕМИЯ", onDemand: false },
                    { name: "129-ТО ОУ", onDemand: false },
                    { name: "УЛ. ЧЕРКОВНА", onDemand: false },
                    { name: "УЛ. ОБОРИЩЕ", onDemand: false },
                    { name: "УЛ. КАЛИМАНЦИ", onDemand: false },
                    { name: "РУМЪНСКО ПОСОЛСТВО", onDemand: false },
                    { name: "УЛ. ХЕМУС", onDemand: false },
                    { name: "УЛ. АЛЕКСАНДЪР ЖЕНДОВ", onDemand: false },
                    { name: "УЛ. НИКОЛАЙ КОПЕРНИК", onDemand: false },
                    { name: "НУ ЗА ТАНЦОВО ИЗКУСТВО", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "Ж.К. СЛАТИНА", onDemand: false },
                    { name: "ВТУ Т. КАБЛЕШКОВ", onDemand: false },
                    { name: "СЛАТИНА БУЛГАРПЛОД", onDemand: false },
                    { name: "БКС СРЕДЕЦ", onDemand: false },
                    { name: "АВТОБАЗА ИСКЪР", onDemand: false },
                ]
            }
        ]
    },
	"bus-10": {
        number: "10",
        type: "bus",
        directions: [
            {
                name: "ДИМИТЪР МИЛЕНКОВ",
                stops: [
                    { name: "КВ. БУСМАНЦИ", onDemand: false },
                    { name: "ДЕТСКИ ДОМ", onDemand: false },
                    { name: "ТРЪНСКА МАХАЛА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "ЦЕНТЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "КВ. АБДОВИЦА", onDemand: false },
                    { name: "ЦЕНТЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "УЛ. 5010", onDemand: false },
                    { name: "УЛ. ПОРУЧИК ХР. ТОПРАКЧИЕВ", onDemand: false },
                    { name: "УЛ. 5007", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ СОФИЙСКА СВЕТА ГОРА", onDemand: false },
                    { name: "УЛ. ПОДПОР. ЙОРДАН ТОДОРОВ", onDemand: false },
                    { name: "ТЮФ", onDemand: false },
                    { name: "ТЕХНОТЕСТ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА ЛЕТИЩЕТО", onDemand: false },
                    { name: "Ж.К. ДРУЖБА 1", onDemand: false },
                    { name: "БУЛ. КРЪСТЬО ПАСТУХОВ", onDemand: false },
                    { name: "28-МИ ДКЦ", onDemand: false },
                    { name: "28-МИ ПОЩЕНСКИ КЛОН", onDemand: false },
					{ name: "ГАРА ИСКЪР", onDemand: false },
					{ name: "НАЧАЛО КВ Д. МИЛЕНКОВ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА", onDemand: false },
					{ name: "КВ. ДИМИТЪР МИЛЕНКОВ", onDemand: false },
                ]
            },
            {
                name: "БУСМАНЦИ",
                stops: [
                    { name: "КВ. ДИМИТЪР МИЛЕНКОВ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА", onDemand: false },
                    { name: "НАЧАЛО КВ Д. МИЛЕНКОВ", onDemand: false },
                    { name: "ГАРА ИСКЪР", onDemand: false },
                    { name: "28-МИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "28-МИ ДКЦ", onDemand: false },
                    { name: "БУЛ. КРЪСТЬО ПАСТУХОВ", onDemand: false },
                    { name: "Ж.К. ДРУЖБА 1", onDemand: false },
                    { name: "РАЗКЛОНА ЗА ЛЕТИЩЕТО", onDemand: false },
                    { name: "ТЕХНОТЕСТ", onDemand: false },
                    { name: "ТЮФ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ СОФИЙСКА СВЕТА ГОРА", onDemand: false },
                    { name: "УЛ. ПОДПОР. ЙОРДАН ТОДОРОВ", onDemand: false },
                    { name: "УЛ. 5007", onDemand: false },
                    { name: "УЛ. ПОРУЧИК ХР. ТОПРАКЧИЕВ", onDemand: false },
                    { name: "УЛ. 5010", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
                    { name: "ЦЕНТЪР КВ. АБДОВИЦА", onDemand: false },
					{ name: "КВ. АБДОВИЦА", onDemand: false },
					{ name: "ЦЕНТЪР КВ. АБДОВИЦА", onDemand: false },
					{ name: "ТРЪНСКА МАХАЛА", onDemand: false },
					{ name: "ДЕТСКИ ДОМ", onDemand: false },
					{ name: "КВ. БУСМАНЦИ", onDemand: false },
                ]
            }
        ]
    },
	"bus-11": {
        number: "11",
        type: "bus",
        directions: [
            {
                name: "ОВЧА КУПЕЛ 2",
                stops: [
                    { name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                    { name: "Ж.К. СЛАТИНА", onDemand: false },
                    { name: "148-МО СОУ", onDemand: false },
                    { name: "109-ТО ОУ", onDemand: false },
                    { name: "УЛ. БОЯН МАГЕСНИК", onDemand: false },
                    { name: "УЛ. ВЕЛЧО АТАНАСОВ", onDemand: false },
                    { name: "ГАРА ПОДУЯНЕ", onDemand: false },
                    { name: "ТЕАТЪР СОФИЯ", onDemand: false },
                    { name: "УЛ. БЯЛО МОРЕ", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                    { name: "БУЛ. ХРИСТО БОТЕВ", onDemand: false },
                    { name: "УЛ. ОПЪЛЧЕНСКА", onDemand: false },
                    { name: "Ж.К. БАНИШОРА", onDemand: false },
                    { name: "УЛ. ЦАР СИМЕОН", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ К. ВЕЛИЧКОВ", onDemand: false },
                    { name: "ПАРК СВ. СВ. ПЕТЪР И ПАВЕЛ", onDemand: false },
                    { name: "УЛ. ОСВОБОЖДЕНИЕ", onDemand: false },
					{ name: "БУЛ. ВАРДАР", onDemand: false },
					{ name: "УЛ. ДОБРОТИЧ", onDemand: false },
					{ name: "Ж.К. КРАСНА ПОЛЯНА", onDemand: false },
					{ name: "БАЛКАНКАР АД", onDemand: false },
					{ name: "МЕТРОСТАНЦИЯ ОВЧА КУПЕЛ", onDemand: false },
					{ name: "УЛ. ЛИЛЯЧЕ", onDemand: false },
					{ name: "ОЦ ОВЧА КУПЕЛ", onDemand: false },
					{ name: "БЛ. 519 Ж.К. ОВЧА КУПЕЛ 1", onDemand: false },
					{ name: "ТЪРГОВСКИ ЦЕНТЪР ОВЧА КУПЕЛ", onDemand: false },
					{ name: "УЛ. ПРОМИШЛЕНА", onDemand: false },
					{ name: "БЛ. 32 Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
					{ name: "БЛ. 25 Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
					{ name: "ПАЗАРА ОВЧА КУПЕЛ", onDemand: false },
					{ name: "Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
                ]
            },
            {
                name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ",
                stops: [
                    { name: "Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
                    { name: "ПАЗАРА ОВЧА КУПЕЛ", onDemand: false },
                    { name: "БЛ. 25 Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
                    { name: "БЛ. 32 Ж.К. ОВЧА КУПЕЛ 2", onDemand: false },
                    { name: "УЛ. ПРОМИШЛЕНА", onDemand: false },
                    { name: "ТЪРГОВСКИ ЦЕНТЪР ОВЧА КУПЕЛ", onDemand: false },
                    { name: "БЛ. 519 Ж.К. ОВЧА КУПЕЛ 1", onDemand: false },
                    { name: "ОЦ ОВЧА КУПЕЛ", onDemand: false },
                    { name: "УЛ. ЛИЛЯЧЕ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ ОВЧА КУПЕЛ", onDemand: false },
                    { name: "БАЛКАНКАР АД", onDemand: false },
                    { name: "Ж.К. КРАСНА ПОЛЯНА", onDemand: false },
                    { name: "УЛ. ДОБРОТИЧ", onDemand: false },
                    { name: "БУЛ. ВАРДАР", onDemand: false },
                    { name: "УЛ. ОСВОБОЖДЕНИЕ", onDemand: false },
                    { name: "ПАРК СВ. СВ. ПЕТЪР И ПАВЕЛ", onDemand: false },
                    { name: "МЕТРОСТАНЦИЯ К. ВЕЛИЧКОВ", onDemand: false },
                    { name: "УЛ. ЦАР СИМЕОН", onDemand: false },
					{ name: "Ж.К. БАНИШОРА", onDemand: false },
					{ name: "УЛ. ОПЪЛЧЕНСКА", onDemand: false },
					{ name: "БУЛ. ХРИСТО БОТЕВ", onDemand: false },
					{ name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "УЛ. БЯЛО МОРЕ", onDemand: false },
					{ name: "ТЕАТЪР СОФИЯ", onDemand: false },
					{ name: "ГАРА ПОДУЯНЕ", onDemand: false },
					{ name: "УЛ. ВЕЛЧО АТАНАСОВ", onDemand: false },
					{ name: "УЛ. БОЯН МАГЕСНИК", onDemand: false },
					{ name: "109-ТО ОУ", onDemand: false },
					{ name: "148-МО СОУ", onDemand: false },
					{ name: "Ж.К. СЛАТИНА", onDemand: false },
					{ name: "АВТОСТАНЦИЯ ГЕО МИЛЕВ", onDemand: false },
                ]
            }
        ]
    },
	"bus-12": {
        number: "12",
        type: "bus",
        directions: [
            {
                name: "ДОЛНИ БОГРОВ",
                stops: [
                    { name: "АВТОСТАНЦИЯ ИЗТОК", onDemand: false },
                    { name: "УЛ. СТ. ДОСПЕВСКИ", onDemand: false },
                    { name: "БЛ. 11 Ж.К. ЛЕВСКИ В", onDemand: false },
                    { name: "УЛ. СТАНИСЛАВ ДОСПЕВСКИ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "УЛ. 61", onDemand: false },
                    { name: "УЛ. 3", onDemand: false },
                    { name: "МОСТА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "ПЛОЩАДА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР - КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МАХАЛА БАТАРЕЯТА", onDemand: false },
                    { name: "КАНТОНА", onDemand: false },
                    { name: "МАГИСТРАЛА ХЕМУС", onDemand: false },
                    { name: "ЕЗЕРОТО", onDemand: false },
                    { name: "РАЗКЛОНА ЗА Д. БОГРОВ", onDemand: false },
                    { name: "МОСТА С. ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "КМЕТСТВО ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "СЕЛО ДОЛНИ БОГРОВ", onDemand: false },
                ]
            },
            {
                name: "АВТОСТАНЦИЯ ИЗТОК",
                stops: [
                    { name: "СЕЛО ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "КМЕТСТВО ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "МОСТА С. ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА С. ДОЛНИ БОГРОВ", onDemand: false },
                    { name: "ЕЗЕРОТО", onDemand: false },
                    { name: "МАГИСТРАЛА ХЕМУС", onDemand: false },
                    { name: "КАНТОНА", onDemand: false },
                    { name: "МАХАЛА БАТАРЕЯТА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР - КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "ПЛОЩАДА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МОСТА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "УЛ. 3", onDemand: false },
                    { name: "УЛ. 61", onDemand: false },
                    { name: "РАЗКЛОНА ЗА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "БЛ. 11 Ж.К. ЛЕВСКИ В", onDemand: false },
                    { name: "УЛ. СТ. ДОСПЕВСКИ", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ИЗТОК", onDemand: false },
                ]
            }
        ]
    },
	"bus-14": {
        number: "14",
        type: "bus",
        directions: [
            {
                name: "ГАРА ИСКЪР",
                stops: [
                    { name: "АВТОСТАНЦИЯ ИЗТОК", onDemand: false },
                    { name: "УЛ. СТ. ДОСПЕВСКИ", onDemand: false },
                    { name: "БЛ. 11 Ж.К. ЛЕВСКИ В", onDemand: false },
                    { name: "УЛ. СТАНИСЛАВ ДОСПЕВСКИ", onDemand: false },
                    { name: "РАЗКЛОНА ЗА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "УЛ. 61", onDemand: false },
                    { name: "УЛ. 3", onDemand: false },
                    { name: "МОСТА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "ПЛОЩАДА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР - КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МАХАЛА БАТАРЕЯТА", onDemand: false },
                    { name: "КАНТОНА", onDemand: false },
                    { name: "РАБОТИЛНИЦАТА", onDemand: false },
                    { name: "НОВА МАХАЛА", onDemand: true },
                    { name: "НОВА ВРАЖДЕБНА", onDemand: false },
                    { name: "ПО ЖЕЛАНИЕ", onDemand: true },
                    { name: "УЛ. ЗАД СЕЛО", onDemand: false },
                    { name: "СЕЛО КРИВИНА", onDemand: false },
					{ name: "ЦЕНТЪРА С. КРИВИНА", onDemand: false },
					{ name: "УЛ. ЛЮЛЯК", onDemand: false },
					{ name: "ПАРКА С. КРИВИНА", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА КРИВИНА", onDemand: false },
					{ name: "РИТЕКС АД", onDemand: false },
					{ name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
					{ name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
					{ name: "КВ. ВИДНИТЕ", onDemand: false },
					{ name: "КВ. ВИДНИТЕ", onDemand: false },
					{ name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
					{ name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
					{ name: "СТАДИОНА КАЗИЧЕНЕ", onDemand: false },
					{ name: "БЕТОНОВ ВЪЗЕЛ КАЗИЧЕНЕ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА КАЗИЧЕНЕ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА БУСМАНЦИ", onDemand: false },
					{ name: "КВ. БУСМАНЦИ", onDemand: false },
					{ name: "ДЕТСКИ ДОМ", onDemand: false },
					{ name: "ТРЪНСКА МАХАЛА", onDemand: false },
					{ name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
					{ name: "ГАРА ИСКЪР", onDemand: false },
                ]
            },
            {
                name: "АВТОСТАНЦИЯ ИЗТОК",
                stops: [
                    { name: "ГАРА ИСКЪР", onDemand: false },
                    { name: "28-МИ ПОЩЕНСКИ КЛОН", onDemand: false },
                    { name: "28-МИ ДКЦ", onDemand: false },
                    { name: "БУЛ. КРЪСТЬО ПАСТУХОВ", onDemand: false },
                    { name: "Ж.К. ДРУЖБА 1", onDemand: false },
                    { name: "РАЗКЛОНА ЗА ЛЕТИЩЕТО", onDemand: false },
					{ name: "ТЕХНОТЕСТ", onDemand: false },
					{ name: "ТЮФ", onDemand: false },
					{ name: "УЛ. ПОДПОР. ЙОРДАН ТОДОРОВ", onDemand: false },
					{ name: "УЛ. 5007", onDemand: false },
					{ name: "УЛ. ПОРУЧИК ХР. ТОПРАКЧИЕВ", onDemand: false },
					{ name: "УЛ. 5010", onDemand: false },
					{ name: "МОСТА НА Р. ИСКЪР КВ. АБДОВИЦА", onDemand: false },
					{ name: "ТРЪНСКА МАХАЛА", onDemand: false },
					{ name: "ДЕТСКИ ДОМ", onDemand: false },
					{ name: "КВ. БУСМАНЦИ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА БУСМАНЦИ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА КАЗИЧЕНЕ", onDemand: false },
					{ name: "БЕТОНОВ ВЪЗЕЛ КАЗИЧЕНЕ", onDemand: false },
					{ name: "СТАДИОНА КАЗИЧЕНЕ", onDemand: false },
					{ name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
					{ name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
					{ name: "КВ. ВИДНИТЕ", onDemand: false },
					{ name: "КВ. ВИДНИТЕ", onDemand: false },
					{ name: "КМЕТСТВО КАЗИЧЕНЕ", onDemand: false },
					{ name: "СЕЛО КАЗИЧЕНЕ", onDemand: false },
					{ name: "РИТЕКС АД", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА КРИВИНА", onDemand: false },
					{ name: "ПАРКА С. КРИВИНА", onDemand: false },
					{ name: "УЛ. ЛЮЛЯК", onDemand: false },
					{ name: "ЦЕНТЪРА С. КРИВИНА", onDemand: false },
					{ name: "СЕЛО КРИВИНА", onDemand: false },
					{ name: "УЛ. ЗАД СЕЛО", onDemand: false },
					{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
					{ name: "НОВА ВРАЖДЕБНА", onDemand: false },
					{ name: "НОВА МАХАЛА", onDemand: true },
					{ name: "РАБОТИЛНИЦАТА", onDemand: false },
					{ name: "КАНТОНА", onDemand: false },
					{ name: "КАНТОНА", onDemand: false },
                    { name: "КАНТОНА", onDemand: false },
                    { name: "МАХАЛА БАТАРЕЯТА", onDemand: false },
                    { name: "МОСТА НА Р. ИСКЪР - КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "ПЛОЩАДА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "МОСТА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "УЛ. 3", onDemand: false },
                    { name: "УЛ. 61", onDemand: false },
                    { name: "РАЗКЛОНА ЗА КВ. ВРАЖДЕБНА", onDemand: false },
                    { name: "БЛ. 11 Ж.К. ЛЕВСКИ В", onDemand: false },
                    { name: "УЛ. СТ. ДОСПЕВСКИ", onDemand: false },
                    { name: "АВТОСТАНЦИЯ ИЗТОК", onDemand: false },
                ]
            }
        ]
    },
	"bus-18": {
        number: "18",
        type: "bus",
        directions: [
            {
                name: "МЕЛНИЦАТА ЧЕПИНЦИ",
                stops: [
                    { name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
                    { name: "КВ. МАЛАШЕВЦИ", onDemand: false },
                    { name: "МОСТА НА ВЛАДАЙСКА РЕКА", onDemand: false },
                    { name: "ПАЗАР МАЛАШЕВЦИ", onDemand: false },
                    { name: "ГРОБИЩЕН ПАРК МАЛАШЕВЦИ", onDemand: false },
                    { name: "УЛ. ЧЕПИНСКО ШОСЕ", onDemand: false },
                    { name: "ПТИЦЕФЕРМАТА", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА", onDemand: false },
                    { name: "СКЛАДОВА БАЗА - ЧЕПИНСКО ШОСЕ", onDemand: false },
                    { name: "ПЕТТЕ МОГИЛИ", onDemand: false },
                    { name: "МОСТА НА РЕКА ИСКЪР", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "ЗЕЛЕНЧУКОВА ГРАДИНА", onDemand: false },
                    { name: "КАРИЕРНИ МАТЕРИАЛИ АД", onDemand: false },
                    { name: "СЕЛО ЧЕПИНЦИ", onDemand: true },
                    { name: "ПЛ. ВИТОША", onDemand: false },
                    { name: "УЛ. НАДЕЖДА", onDemand: true },
                    { name: "МЕЛНИЦАТА ЧЕПИНЦИ", onDemand: false },
                ]
            },
            {
                name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ",
                stops: [
                    { name: "МЕЛНИЦАТА ЧЕПИНЦИ", onDemand: false },
                    { name: "УЛ. НАДЕЖДА", onDemand: false },
                    { name: "ПЛ. ВИТОША", onDemand: false },
                    { name: "СЕЛО ЧЕПИНЦИ", onDemand: false },
                    { name: "КАРИЕРНИ МАТЕРИАЛИ АД", onDemand: false },
                    { name: "ЗЕЛЕНЧУКОВА ГРАДИНА", onDemand: false },
					{ name: "ОПИТНА СТАНЦИЯ", onDemand: false },
					{ name: "МОСТА НА РЕКА ИСКЪР", onDemand: false },
					{ name: "ПЕТТЕ МОГИЛИ", onDemand: false },
					{ name: "СКЛАДОВА БАЗА - ЧЕПИНСКО ШОСЕ", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА", onDemand: false },
					{ name: "ПТИЦЕФЕРМАТА", onDemand: false },
					{ name: "УЛ. ЧЕПИНСКО ШОСЕ", onDemand: false },
					{ name: "ГРОБИЩЕН ПАРК МАЛАШЕВЦИ", onDemand: false },
					{ name: "ПАЗАР МАЛАШЕВЦИ", onDemand: false },
					{ name: "МОСТА НА ВЛАДАЙСКА РЕКА", onDemand: false },
					{ name: "КВ. МАЛАШЕВЦИ", onDemand: false },
					{ name: "УЛ. ПЪРВА БЪЛГАРСКА АРМИЯ", onDemand: false },
					{ name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
                ]
            }
        ]
    },
	"bus-20": {
        number: "20",
        type: "bus",
        directions: [
            {
                name: "ЛЪВОВ МОСТ",
                stops: [
                    { name: "СЕЛО ЛОКОРСКО", onDemand: false },
                    { name: "УЛ. ВЕСКО ВЕСЕЛИНОВ", onDemand: false },
                    { name: "НАЧАЛО С. ЛОКОРСКО", onDemand: false },
                    { name: "ГОРСКО СТОПАНСТВО", onDemand: false },
                    { name: "ГАРА ЧЕПИНЦИ", onDemand: false },
                    { name: "160-ТО ОУ", onDemand: false },
                    { name: "СЕЛО ЧЕПИНЦИ", onDemand: false },
                    { name: "УЛ. ОРФЕЙ", onDemand: false },
                    { name: "ГРОБИЩЕН ПАРК НЕГОВАН", onDemand: false },
                    { name: "СЕЛО НЕГОВАН", onDemand: false },
                    { name: "ЕЛ. КАНТОН", onDemand: false },
                    { name: "ЗЕЛЕНЧУКОВА ГРАДИНА", onDemand: false },
                    { name: "ОПИТНА СТАНЦИЯ", onDemand: false },
                    { name: "МОСТА НА РЕКА ИСКЪР", onDemand: false },
                    { name: "ПЕТТЕ МОГИЛИ", onDemand: true },
                    { name: "СКЛАДОВА БАЗА - ЧЕПИНСКО ШОСЕ", onDemand: false },
                    { name: "ПРОМИШЛЕНА ЗОНА", onDemand: true },
                    { name: "ПТИЦЕФЕРМАТА", onDemand: false },
					{ name: "УЛ. ЧЕПИНСКО ШОСЕ", onDemand: false },
					{ name: "ГРОБИЩЕН ПАРК МАЛАШЕВЦИ", onDemand: false },
					{ name: "ПАЗАР МАЛАШЕВЦИ", onDemand: false },
					{ name: "МОСТА НА ВЛАДАЙСКА РЕКА", onDemand: false },
					{ name: "КВ. МАЛАШЕВЦИ", onDemand: false },
					{ name: "УЛ. РОЯК", onDemand: false },
					{ name: "КАТОЛИЧЕСКИ ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                ]
            },
            {
                name: "ЛОКОРСКО",
                stops: [
                    { name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                    { name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
                    { name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "УЛ. КАМЕНОДЕЛСКА", onDemand: false },
					{ name: "УЛ. ПЪРВА БЪЛГАРСКА АРМИЯ", onDemand: false },
					{ name: "КВ. МАЛАШЕВЦИ", onDemand: false },
					{ name: "МОСТА НА ВЛАДАЙСКА РЕКА", onDemand: false },
					{ name: "ПАЗАР МАЛАШЕВЦИ", onDemand: false },
					{ name: "ГРОБИЩЕН ПАРК МАЛАШЕВЦИ", onDemand: false },
					{ name: "УЛ. ЧЕПИНСКО ШОСЕ", onDemand: false },
					{ name: "ПТИЦЕФЕРМАТА", onDemand: false },
					{ name: "ПРОМИШЛЕНА ЗОНА", onDemand: false },
					{ name: "СКЛАДОВА БАЗА - ЧЕПИНСКО ШОСЕ", onDemand: false },
					{ name: "ПЕТТЕ МОГИЛИ", onDemand: false },
					{ name: "МОСТА НА РЕКА ИСКЪР", onDemand: false },
					{ name: "ОПИТНА СТАНЦИЯ", onDemand: false },
					{ name: "ЗЕЛЕНЧУКОВА ГРАДИНА", onDemand: false },
					{ name: "ЕЛ. КАНТОН", onDemand: false },
					{ name: "СЕЛО НЕГОВАН", onDemand: false },
					{ name: "ГРОБИЩЕН ПАРК НЕГОВАН", onDemand: false },
					{ name: "УЛ. ОРФЕЙ", onDemand: false },
					{ name: "СЕЛО ЧЕПИНЦИ", onDemand: false },
					{ name: "УЛ. УЧИЛИЩНА", onDemand: false },
					{ name: "160-ТО ОУ", onDemand: false },
					{ name: "ГАРА ЧЕПИНЦИ", onDemand: false },
					{ name: "ГОРСКО СТОПАНСТВО", onDemand: false },
					{ name: "НАЧАЛО С. ЛОКОРСКО", onDemand: false },
					{ name: "УЛ. ВЕСКО ВЕСЕЛИНОВ", onDemand: false },
					{ name: "СЕЛО ЛОКОРСКО", onDemand: false },
                ]
            }
        ]
    },
	"bus-21": {
        number: "21",
        type: "bus",
        directions: [
            {
                name: "ВОЙНЕГОВЦИ",
                stops: [
                    { name: "ЦЕНТРАЛНА ГАРА", onDemand: false },
                    { name: "УЛ. КОЗЛОДУЙ", onDemand: false },
                    { name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
                    { name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
                    { name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
                    { name: "УЛ. ПОЩЕНСКА", onDemand: false },
                    { name: "УЛ. ОДЕСА", onDemand: false },
                    { name: "СЕРВИЗ ПОЛМО", onDemand: false },
                    { name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
                    { name: "ПЛ. БИРИМИРЦИ", onDemand: false },
                    { name: "60-ТО ОУ", onDemand: false },
                    { name: "КВ. БЕНКОВСКИ", onDemand: true },
                    { name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
                    { name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: true },
                    { name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
					{ name: "СЕЛО КУБРАТОВО", onDemand: false },
					{ name: "УЛ. СИНЧЕЦ", onDemand: false },
					{ name: "177-МО ОУ", onDemand: false },
					{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
					{ name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
					{ name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
					{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
					{ name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
					{ name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
					{ name: "СЕЛО ВОЙНЕГОВЦИ", onDemand: false },
                ]
            },
            {
                name: "ЦЕНТРАЛНА ГАРА",
                stops: [
                    { name: "СЕЛО ВОЙНЕГОВЦИ", onDemand: false },
                    { name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
                    { name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
                    { name: "ПО ЖЕЛАНИЕ", onDemand: true },
                    { name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
                    { name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
					{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
					{ name: "177-МО ОУ", onDemand: false },
					{ name: "УЛ. СИНЧЕЦ", onDemand: false },
					{ name: "СЕЛО КУБРАТОВО", onDemand: false },
					{ name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
					{ name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: false },
					{ name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
					{ name: "КВ. БЕНКОВСКИ", onDemand: false },
					{ name: "60-ТО ОУ", onDemand: false },
					{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
					{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
					{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
					{ name: "УЛ. ОДЕСА", onDemand: false },
					{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
					{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
					{ name: "КАТОЛИЧЕСКИ ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
					{ name: "УЛ. КЛОКОТНИЦА", onDemand: false },
					{ name: "ЦЕНТРАЛНА ГАРА", onDemand: false },
                ]
            }
        ]
    },
	"bus-22": {
        number: "22",
        type: "bus",
        directions: [
            {
                name: "ПОДГУМЕР",
                stops: [
                    { name: "ЦЕНТРАЛНА ГАРА", onDemand: false },
                    { name: "УЛ. КОЗЛОДУЙ", onDemand: false },
                    { name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
                    { name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
                    { name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
                    { name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
                    { name: "УЛ. ПОЩЕНСКА", onDemand: false },
                    { name: "УЛ. ОДЕСА", onDemand: false },
                    { name: "СЕРВИЗ ПОЛМО", onDemand: false },
                    { name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
                    { name: "ПЛ. БИРИМИРЦИ", onDemand: false },
                    { name: "60-ТО ОУ", onDemand: false },
                    { name: "КВ. БЕНКОВСКИ", onDemand: true },
                    { name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
                    { name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: true },
                    { name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
					{ name: "СЕЛО КУБРАТОВО", onDemand: false },
					{ name: "УЛ. СИНЧЕЦ", onDemand: false },
					{ name: "177-МО ОУ", onDemand: false },
					{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
					{ name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
					{ name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
					{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
					{ name: "УЛ. МЛАДОСТ", onDemand: true },
					{ name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
					{ name: "СЕЛО ПОДГУМЕР", onDemand: false },
					{ name: "В. З. ПОДГУМЕР", onDemand: true },
					{ name: "БОЛНИЦАТА ПОДГУМЕР", onDemand: false },
                ]
            },
            {
                name: "ЦЕНТРАЛНА ГАРА",
                stops: [
                    { name: "БОЛНИЦАТА ПОДГУМЕР", onDemand: false },
                    { name: "В. З. ПОДГУМЕР", onDemand: true },
                    { name: "СЕЛО ПОДГУМЕР", onDemand: false },
                    { name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
					{ name: "УЛ. МЛАДОСТ", onDemand: true },
					{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
                    { name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
                    { name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
					{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
					{ name: "177-МО ОУ", onDemand: false },
					{ name: "УЛ. СИНЧЕЦ", onDemand: false },
					{ name: "СЕЛО КУБРАТОВО", onDemand: false },
					{ name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
					{ name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: false },
					{ name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
					{ name: "КВ. БЕНКОВСКИ", onDemand: false },
					{ name: "60-ТО ОУ", onDemand: false },
					{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
					{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
					{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
					{ name: "УЛ. ОДЕСА", onDemand: false },
					{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
					{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
					{ name: "КАТОЛИЧЕСКИ ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ЦЕНТРАЛЕН ГРОБИЩЕН ПАРК", onDemand: false },
					{ name: "ХЛАДИЛЕН ЗАВОД", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. СТОЧНА ГАРА", onDemand: false },
					{ name: "ПЛ. ЛЪВОВ МОСТ", onDemand: false },
					{ name: "УЛ. КЛОКОТНИЦА", onDemand: false },
					{ name: "ЦЕНТРАЛНА ГАРА", onDemand: false },
                ]
            }
        ]
    },
	"bus-23": {
        number: "23",
        type: "bus",
        directions: [
            {
                name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ",
                stops: [
                    { name: "ГАРА КУРИЛО", onDemand: false },
                    { name: "ПОЩА КВ. КУРИЛО", onDemand: true },
                    { name: "УЛ. АЛ. СТАМБОЛИЙСКИ", onDemand: true },
                    { name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
                    { name: "КВ. ИЗГРЕВ", onDemand: true },
                    { name: "УЛ. ЛИВАДИТЕ", onDemand: true },
                    { name: "СТАРАТА ЧЕШМА", onDemand: true },
                    { name: "КВ. ГНИЛЯНЕ", onDemand: false },
                    { name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false },
                    { name: "БАНЯТА КВ. ГНИЛЯНЕ", onDemand: false },
                    { name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
                    { name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
					{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
					{ name: "177-МО ОУ", onDemand: false },
					{ name: "УЛ. СИНЧЕЦ", onDemand: false },
					{ name: "СЕЛО КУБРАТОВО", onDemand: false },
					{ name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
					{ name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: true },
					{ name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
					{ name: "КВ. БЕНКОВСКИ", onDemand: true },
					{ name: "60-ТО ОУ", onDemand: false },
					{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
					{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
					{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
					{ name: "УЛ. ОДЕСА", onDemand: false },
					{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
					{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
					{ name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
                ]
            },
            {
                name: "ГАРА КУРИЛО",
                stops: [
   					{ name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
    				{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
    				{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
    				{ name: "УЛ. ОДЕСА", onDemand: false },
    				{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
    				{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
    				{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
    				{ name: "60-ТО ОУ", onDemand: false },
    				{ name: "КВ. БЕНКОВСКИ", onDemand: false },
    				{ name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
    				{ name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: false },
    				{ name: "УЛ. КИРИЛ ХРИСТОВ", onDemand: false },
    				{ name: "СЕЛО КУБРАТОВО", onDemand: false },
    				{ name: "УЛ. СИНЧЕЦ", onDemand: false },
    				{ name: "177-МО ОУ", onDemand: false },
    				{ name: "СЕЛО СВЕТОВРАЧАНЕ", onDemand: false },
    				{ name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
    				{ name: "УЛ. ВОЙНЕШКИ ПЪТ", onDemand: true },
    				{ name: "БАНЯТА КВ. ГНИЛЯНЕ", onDemand: false },
    				{ name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false },
    				{ name: "КВ. ГНИЛЯНЕ", onDemand: false },
    				{ name: "СТАРАТА ЧЕШМА", onDemand: true },
    				{ name: "УЛ. ЛИВАДИТЕ", onDemand: true },
    				{ name: "КВ. ИЗГРЕВ", onDemand: true },
    				{ name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
    				{ name: "УЛ. АЛ. СТАМБОЛИЙСКИ", onDemand: false },
    				{ name: "ГАРА КУРИЛО", onDemand: false }
                ]
            }
        ]
    },
	"bus-24": {
        number: "24",
        type: "bus",
        directions: [
            {
                name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ",
                stops: [
                    { name: "МАНАСТИР СВ. МИНА", onDemand: false },
                    { name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: false },
                    { name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
                    { name: "КВ. БЕНКОВСКИ", onDemand: false },
					{ name: "60-ТО ОУ", onDemand: false },
					{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
					{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
					{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
					{ name: "УЛ. ОДЕСА", onDemand: false },
					{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
					{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
					{ name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
                ]
            },
            {
                name: "МАНАСТИР СВ. МИНА",
                stops: [
   					{ name: "АВТОСТАНЦИЯ ОРЛАНДОВЦИ", onDemand: false },
    				{ name: "КВ. ОРЛАНДОВЦИ", onDemand: false },
    				{ name: "УЛ. ПОЩЕНСКА", onDemand: false },
    				{ name: "УЛ. ОДЕСА", onDemand: false },
    				{ name: "СЕРВИЗ ПОЛМО", onDemand: false },
    				{ name: "Ж.П. ПРЕЛЕЗ", onDemand: false },
    				{ name: "ПЛ. БИРИМИРЦИ", onDemand: false },
    				{ name: "60-ТО ОУ", onDemand: false },
    				{ name: "КВ. БЕНКОВСКИ", onDemand: false },
    				{ name: "УЛ. ОБРАДОВСКИ ПЪТ", onDemand: false },
    				{ name: "ПРЕЧИСТВАТЕЛНА СТАНЦИЯ", onDemand: false },
	                { name: "МАНАСТИР СВ. МИНА", onDemand: false },
                ]
            }
        ]
    },
	"bus-26": {
        number: "26",
        type: "bus",
        directions: [
            {
                name: "ОБЕЛЯ 1",
                stops: [
	                { name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false },
  	                { name: "КВ. ГНИЛЯНЕ", onDemand: false },
  	                { name: "СТАРАТА ЧЕШМА", onDemand: true },
  	                { name: "УЛ. ЛИВАДИТЕ", onDemand: true },
  	                { name: "КВ. ИЗГРЕВ", onDemand: true },
  	                { name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
  	                { name: "УЛ. АЛЕКСАНДЪР СТАМБОЛИЙСКИ", onDemand: true },
  	                { name: "ПОЩА КВ. КУРИЛО", onDemand: true },
  	                { name: "ГАРА КУРИЛО", onDemand: false },
  	                { name: "УЛ. БАБА ТОНКА", onDemand: true },
  	                { name: "УЛ. БЪДЕЩЕ", onDemand: true },
  	                { name: "БАЛКАНКЕРАМИК АД", onDemand: true },
  	                { name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
  	                { name: "КВ. КУМАРИЦА", onDemand: true },
  	                { name: "ДЕТСКИ ДОМ", onDemand: false },
  	                { name: "УЛ. ВИШНОВКА", onDemand: true },
  	                { name: "УЛ. ЕДЕЛВАЙС", onDemand: true },
  	                { name: "СЕЛО МИРОВЯНЕ", onDemand: true },
  	                { name: "УЛ. СПОРТИСТ", onDemand: true },
  	                { name: "МИРОВСКО ШОСЕ", onDemand: true },
  	                { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
  	                { name: "КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "УЛ. ДЖЕРМАН", onDemand: true },
  	                { name: "ЦЕНТЪРА КВ. ИЛИЯНЦИ", onDemand: true },
  	                { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
  	                { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
  	                { name: "СОФАРМА АД", onDemand: false },
  	                { name: "ЗАГ ДИНАМИК АД", onDemand: false },
  	                { name: "БУЛ. РОЖЕН", onDemand: false },
  	                { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ХАН КУБРАТ", onDemand: false },
  	                { name: "УЛ. РЕПУБЛИКА", onDemand: false },
  	                { name: "УЛ. ВЪЗРОЖДЕНСКА", onDemand: false },
  	                { name: "УЛ. КОНСТАНТИН БОДИН", onDemand: false },
  	                { name: "УЛ. ХАН КУБРАТ", onDemand: false },
  	                { name: "ОБЩИНА ВРЪБНИЦА", onDemand: false },
  	                { name: "БЛ. 302 Ж.К. НАДЕЖДА-3", onDemand: false },
  	                { name: "БУЛ. ЛОМСКО ШОСЕ", onDemand: false },
  	                { name: "61-ВО ОУ", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ЛОМСКО ШОСЕ", onDemand: false },
  	                { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "БЛ. 245 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "БЛ. 241 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "БЛ. 207 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "УЛ. 9", onDemand: false },
  	                { name: "УЛ. 2", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  	                { name: "БЛ. 119 Ж.К. ОБЕЛЯ-1", onDemand: false },
  	                { name: "БЛ. 111 Ж.К. ОБЕЛЯ-1", onDemand: false },
  	                { name: "Ж.К. ОБЕЛЯ-1", onDemand: false }
                ]
            },
            {
                name: "НАЧАЛО КВ. ГНИЛЯНЕ",
                stops: [
  	                { name: "Ж.К. ОБЕЛЯ-1", onDemand: false },
  	                { name: "БЛ. 111 Ж.К. ОБЕЛЯ-1", onDemand: false },
  	                { name: "БЛ. 119 Ж.К. ОБЕЛЯ-1", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  	                { name: "УЛ. 2", onDemand: false },
  	                { name: "УЛ. 9", onDemand: false },
  	                { name: "БЛ. 207 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "БЛ. 241 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "БЛ. 245 Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ЛОМСКО ШОСЕ", onDemand: false },
  	                { name: "61-ВО ОУ", onDemand: false },
  	                { name: "БУЛ. ЛОМСКО ШОСЕ", onDemand: false },
  	                { name: "БЛ. 302 Ж.К. НАДЕЖДА-3", onDemand: false },
  	                { name: "ОБЩИНА ВРЪБНИЦА", onDemand: false },
  	                { name: "УЛ. ХАН КУБРАТ", onDemand: false },
  	                { name: "УЛ. КОНСТАНТИН БОДИН", onDemand: false },
  	                { name: "УЛ. ВЪЗРОЖДЕНСКА", onDemand: false },
  	                { name: "УЛ. РЕПУБЛИКА", onDemand: false },
  	                { name: "МЕТРОСТАНЦИЯ ХАН КУБРАТ", onDemand: false },
  	                { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
  	                { name: "БУЛ. РОЖЕН", onDemand: false },
  	                { name: "ЗАГ ДИНАМИК АД", onDemand: false },
  	                { name: "СОФАРМА АД", onDemand: false },
  	                { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
  	                { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
  	                { name: "ЦЕНТЪРА КВ. ИЛИЯНЦИ", onDemand: true },
  	                { name: "УЛ. ДЖЕРМАН", onDemand: true },
  	                { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
  	                { name: "МИРОВСКО ШОСЕ", onDemand: true },
  	                { name: "УЛ. СПОРТИСТ", onDemand: true },
  	                { name: "СЕЛО МИРОВЯНЕ", onDemand: true },
  	                { name: "УЛ. ЕДЕЛВАЙС", onDemand: true },
  	                { name: "УЛ. ВИШНОВКА", onDemand: true },
  	                { name: "ДЕТСКИ ДОМ", onDemand: false },
  	                { name: "КВ. КУМАРИЦА", onDemand: true },
  	                { name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
  	                { name: "БАЛКАНКЕРАМИК АД", onDemand: true },
  	                { name: "УЛ. БЪДЕЩЕ", onDemand: true },
  	                { name: "УЛ. БАБА ТОНКА", onDemand: true },
  	                { name: "ГАРА КУРИЛО", onDemand: false },
  	                { name: "ПОЩА КВ. КУРИЛО", onDemand: true },
  	                { name: "УЛ. АЛЕКСАНДЪР СТАМБОЛИЙСКИ", onDemand: true },
  	                { name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
  	                { name: "КВ. ИЗГРЕВ", onDemand: true },
  	                { name: "УЛ. ЛИВАДИТЕ", onDemand: true },
  	                { name: "СТАРАТА ЧЕШМА", onDemand: true },
  	                { name: "КВ. ГНИЛЯНЕ", onDemand: false },
  	                { name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false }
                ]
            }
        ]
    },
	"bus-27": {
        number: "27",
        type: "bus",
        directions: [
            {
                name: "МЕТРОСТАНЦИЯ КНЯГИНЯ МАРИЯ ЛУИЗА",
                stops: [
	                { name: "СЕЛО КЪТИНА", onDemand: false },
	                { name: "СТАРАТА ФУРНА", onDemand: true },
	                { name: "НАЧАЛО С. КЪТИНА", onDemand: true },
	                { name: "МИНАТА", onDemand: true },
	                { name: "СЕПАРАЦИЯТА", onDemand: true },
	                { name: "УЛ. МАЛЬОВИЦА", onDemand: true },
	                { name: "УЛ. ТЕМЕНУГА", onDemand: true },
	                { name: "ПОЩА КВ. КУРИЛО", onDemand: true },
	                { name: "ГАРА КУРИЛО", onDemand: false },
	                { name: "УЛ. БАБА ТОНКА", onDemand: true },
	                { name: "УЛ. БЪДЕЩЕ", onDemand: true },
	                { name: "БАЛКАНКЕРАМИК АД", onDemand: true },
	                { name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
	                { name: "КВ. КУМАРИЦА", onDemand: true },
	                { name: "ДЕТСКИ ДОМ", onDemand: false },
	                { name: "КВ. СЛАВОВЦИ", onDemand: true },
	                { name: "УЛ. РАВНЕЦ", onDemand: true },
	                { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
	                { name: "КВ. ТРЕБИЧ", onDemand: true },
	                { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
	                { name: "УЛ. ДЖЕРМАН", onDemand: true },
	                { name: "ЦЕНТЪРА КВ. ИЛИЯНЦИ", onDemand: true },
	                { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
	                { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
	                { name: "СОФАРМА АД", onDemand: false },
	                { name: "ЗАГ ДИНАМИК АД", onDemand: false },
	                { name: "БУЛ. РОЖЕН", onDemand: false },
	                { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
	                { name: "МЕТРОСТАНЦИЯ КНЯГИНЯ МАРИЯ ЛУИЗА", onDemand: false }
                ]
            },
            {
                name: "КЪТИНА",
                stops: [
  	                { name: "МЕТРОСТАНЦИЯ КНЯГИНЯ МАРИЯ ЛУИЗА", onDemand: false },
  	                { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
  	                { name: "БУЛ. РОЖЕН", onDemand: false },
  	                { name: "ЗАГ ДИНАМИК АД", onDemand: false },
  	                { name: "СОФАРМА АД", onDemand: false },
  	                { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
  	                { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
  	                { name: "ЦЕНТЪРА КВ. ИЛИЯНЦИ", onDemand: true },
  	                { name: "УЛ. ДЖЕРМАН", onDemand: true },
  	                { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "КВ. ТРЕБИЧ", onDemand: true },
  	                { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
  	                { name: "УЛ. РАВНЕЦ", onDemand: true },
  	                { name: "КВ. СЛАВОВЦИ", onDemand: true },
  	                { name: "ДЕТСКИ ДОМ", onDemand: false },
  	                { name: "КВ. КУМАРИЦА", onDemand: true },
  	                { name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
  	                { name: "БАЛКАНКЕРАМИК АД", onDemand: true },
  	                { name: "УЛ. БЪДЕЩЕ", onDemand: true },
  	                { name: "УЛ. БАБА ТОНКА", onDemand: true },
  	                { name: "ГАРА КУРИЛО", onDemand: false },
  	                { name: "ПОЩА КВ. КУРИЛО", onDemand: true },
  	                { name: "УЛ. ТЕМЕНУГА", onDemand: true },
  	                { name: "УЛ. МАЛЬОВИЦА", onDemand: true },
  	                { name: "СЕПАРАЦИЯТА", onDemand: true },
  	                { name: "МИНАТА", onDemand: true },
  	                { name: "НАЧАЛО С. КЪТИНА", onDemand: true },
  	                { name: "СТАРАТА ФУРНА", onDemand: true },
  	                { name: "СЕЛО КЪТИНА", onDemand: false }
                ]
            }
        ]
    },
	"bus-28": {
        number: "28",
        type: "bus",
        directions: [
            {
                name: "ЛОКОРСКО",
                stops: [
{ name: "ЦЕНТЪР С. МРАМОР", onDemand: false },
{ name: "СЕЛО МРАМОР", onDemand: false },
{ name: "КРАЯ С. МРАМОР", onDemand: false },
{ name: "БИОМЕТ ЕООД", onDemand: true },
{ name: "НАЧАЛО С. ЖИТЕН", onDemand: false },
{ name: "УЛ. МИНЗУХАР", onDemand: false },
{ name: "СЕЛО ЖИТЕН", onDemand: false },
{ name: "УЛ. МОГИЛКА", onDemand: false },
{ name: "ПЛ. МЕГДАНА", onDemand: false },
{ name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
{ name: "ЛЕТИЩЕ ДОБРОСЛАВЦИ", onDemand: true },
{ name: "ОРАНЖЕРИЯТА", onDemand: true },
{ name: "КВ. КУМАРИЦА", onDemand: false },
{ name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
{ name: "БАЛКАНКЕРАМИК АД", onDemand: true },
{ name: "УЛ. БЪДЕЩЕ", onDemand: true },
{ name: "УЛ. БАБА ТОНКА", onDemand: true },
{ name: "ГАРА КУРИЛО", onDemand: true },
{ name: "УЛ. АЛЕКСАНДЪР СТАМБОЛИЙСКИ", onDemand: false },
{ name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
{ name: "КВ. ИЗГРЕВ", onDemand: true },
{ name: "УЛ. ЛИВАДИТЕ", onDemand: true },
{ name: "СТАРАТА ЧЕШМА", onDemand: true },
{ name: "КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "БАНЯТА КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
{ name: "УЛ. МЛАДОСТ", onDemand: true },
{ name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
{ name: "СЕЛО ПОДГУМЕР", onDemand: false },
{ name: "СЕЛО ПОДГУМЕР", onDemand: false },
{ name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
{ name: "УЛ. МЛАДОСТ", onDemand: true },
{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
{ name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
{ name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
{ name: "СЕЛО ВОЙНЕГОВЦИ", onDemand: false },
{ name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
{ name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
{ name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
{ name: "СЕЛО СВЕТОВРАЧЕНЕ", onDemand: false },
{ name: "КМЕТСТВО СВЕТОВРАЧЕНЕ", onDemand: false },
{ name: "УЛ. ЛЕСНОВСКА РЕКА", onDemand: false },
{ name: "УЛ. ВРАЧАНСКА", onDemand: false },
{ name: "СЕЛО НЕГОВАН", onDemand: false },
{ name: "ГРОБИЩЕН ПАРК НЕГОВАН", onDemand: false },
{ name: "УЛ. ОРФЕЙ", onDemand: false },
{ name: "СЕЛО ЧЕПИНЦИ", onDemand: false },
{ name: "УЛ. УЧИЛИЩНА", onDemand: false },
{ name: "160-ТО ОУ", onDemand: false },
{ name: "ГАРА ЧЕПИНЦИ", onDemand: false },
{ name: "ГОРСКО СТОПАНСТВО", onDemand: false },
{ name: "НАЧАЛО С. ЛОКОРОСКО", onDemand: false },
{ name: "УЛ. ВЕСКО ВЕСЕЛИНОВ", onDemand: false },
{ name: "СЕЛО ЛОКОРОСКО", onDemand: false }
                ]
            },
            {
                name: "МРАМОР",
                stops: [
{ name: "СЕЛО ЛОКОРОСКО", onDemand: false },
{ name: "УЛ. ВЕСКО ВЕСЕЛИНОВ", onDemand: false },
{ name: "НАЧАЛО С. ЛОКОРОСКО", onDemand: false },
{ name: "ГОРСКО СТОПАНСТВО", onDemand: false },
{ name: "ГАРА ЧЕПИНЦИ", onDemand: false },
{ name: "160-ТО ОУ", onDemand: false },
{ name: "УЛ. УЧИЛИЩНА", onDemand: false },
{ name: "СЕЛО ЧЕПИНЦИ", onDemand: false },
{ name: "УЛ. ОРФЕЙ", onDemand: false },
{ name: "ГРОБИЩЕН ПАРК НЕГОВАН", onDemand: false },
{ name: "СЕЛО НЕГОВАН", onDemand: false },
{ name: "УЛ. ВРАЧАНСКА", onDemand: false },
{ name: "УЛ. ЛЕСНОВСКА РЕКА", onDemand: false },
{ name: "КМЕТСТВО СВЕТОВРАЧЕНЕ", onDemand: false },
{ name: "СЕЛО СВЕТОВРАЧЕНЕ", onDemand: false },
{ name: "УЛ. ТРАКИЙСКА МОГИЛА", onDemand: false },
{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
{ name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
{ name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
{ name: "СЕЛО ВОЙНЕГОВЦИ", onDemand: false },
{ name: "ЦЕНТЪР С. ВОЙНЕГОВЦИ", onDemand: false },
{ name: "НАЧАЛО С. ВОЙНЕГОВЦИ", onDemand: true },
{ name: "ПО ЖЕЛАНИЕ", onDemand: true },
{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
{ name: "УЛ. МЛАДОСТ", onDemand: true },
{ name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
{ name: "СЕЛО ПОДГУМЕР", onDemand: false },
{ name: "СЕЛО ПОДГУМЕР", onDemand: false },
{ name: "ЦЕНТЪР С. ПОДГУМЕР", onDemand: false },
{ name: "УЛ. МЛАДОСТ", onDemand: true },
{ name: "НАЧАЛО С. ПОДГУМЕР", onDemand: true },
{ name: "БАНЯТА КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "НАЧАЛО КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "КВ. ГНИЛЯНЕ", onDemand: false },
{ name: "СТАРАТА ЧЕШМА", onDemand: true },
{ name: "УЛ. ЛИВАДИТЕ", onDemand: true },
{ name: "КВ. ИЗГРЕВ", onDemand: true },
{ name: "КАУЧУКОВ ЗАВОД ЗЕБРА", onDemand: true },
{ name: "УЛ. АЛЕКСАНДЪР СТАМБОЛИЙСКИ", onDemand: false },
{ name: "ГАРА КУРИЛО", onDemand: true },
{ name: "УЛ. БАБА ТОНКА", onDemand: true },
{ name: "УЛ. БЪДЕЩЕ", onDemand: true },
{ name: "БАЛКАНКЕРАМИК АД", onDemand: true },
{ name: "ОБЩИНА НОВИ ИСКЪР", onDemand: true },
{ name: "КВ. КУМАРИЦА", onDemand: false },
{ name: "ОРАНЖЕРИЯТА", onDemand: true },
{ name: "ЛЕТИЩЕ ДОБРОСЛАВЦИ", onDemand: true },
{ name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
{ name: "ПЛ. МЕГДАНА", onDemand: false },
{ name: "УЛ. МОГИЛКА", onDemand: false },
{ name: "СЕЛО ЖИТЕН", onDemand: false },
{ name: "УЛ. МИНЗУХАР", onDemand: false },
{ name: "НАЧАЛО С. ЖИТЕН", onDemand: false },
{ name: "БИОМЕТ ЕООД", onDemand: true },
{ name: "КРАЯ С. МРАМОР", onDemand: false },
{ name: "СЕЛО МРАМОР", onDemand: false },
{ name: "ЦЕНТЪР С. МРАМОР", onDemand: false }
                ]
            }
        ]
    },
	"bus-29": {
        number: "29",
        type: "bus",
        directions: [
            {
                name: "БАЛША",
                stops: [
  { name: "ГАРА СОФИЯ СЕВЕР", onDemand: false },
  { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
  { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
  { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
  { name: "УЛ. КИРИЛ БЛАГОЕВ", onDemand: false },
  { name: "УЛ. ДЖЕРМАН", onDemand: false },
  { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
  { name: "КВ. ТРЕБИЧ", onDemand: true },
  { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
  { name: "МИРОВСКО ШОСЕ", onDemand: true },
  { name: "УЛ. СПОРТИСТ", onDemand: true },
  { name: "СЕЛО МИРОВЯНЕ", onDemand: true },
  { name: "УЛ. ЕДЕЛВАЙС", onDemand: true },
  { name: "УЛ. ВИШНОВСКА", onDemand: true },
  { name: "УЛ. КРУШАТА", onDemand: true },
  { name: "УЛ. РАВНЕЦ", onDemand: true },
  { name: "КВ. СЛАВОВЦИ", onDemand: true },
  { name: "ДЕТСКИ ДОМ", onDemand: false },
  { name: "КВ. КУМАРИЦА", onDemand: false },
  { name: "ОРАНЖЕРИЯТА", onDemand: true },
  { name: "ЛЕТИЩЕ ДОБРОСЛАВЦИ", onDemand: true },
  { name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "КРАЯ С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "МАНАСТИР СВ. ТЕОДОР СТРАТИЛАТ", onDemand: true },
  { name: "УЛ. ВРЪБЛИНА", onDemand: false },
  { name: "КМЕТСТВО БАЛША", onDemand: false },
  { name: "ПО ЖЕЛАНИЕ", onDemand: true },
  { name: "УЛ. СТАРА ПЛАНИНА", onDemand: false },
  { name: "СЕЛО БАЛША", onDemand: false }
                ]
            },
            {
                name: "ГАРА СОФИЯ СЕВЕР",
                stops: [
  { name: "СЕЛО БАЛША", onDemand: false },
  { name: "УЛ. СТАРА ПЛАНИНА", onDemand: false },
  { name: "ПО ЖЕЛАНИЕ", onDemand: true },
  { name: "КМЕТСТВО БАЛША", onDemand: false },
  { name: "УЛ. ВРЪБЛИНА", onDemand: false },
  { name: "МАНАСТИР СВ. ТЕОДОР СТРАТИЛАТ", onDemand: true },
  { name: "КРАЯ С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "ЛЕТИЩЕ ДОБРОСЛАВЦИ", onDemand: true },
  { name: "ОРАНЖЕРИЯТА", onDemand: true },
  { name: "КВ. КУМАРИЦА", onDemand: false },
  { name: "ДЕТСКИ ДОМ", onDemand: false },
  { name: "КВ. СЛАВОВЦИ", onDemand: true },
  { name: "УЛ. РАВНЕЦ", onDemand: true },
  { name: "УЛ. КРУШАТА", onDemand: true },
  { name: "УЛ. ВИШНОВСКА", onDemand: true },
  { name: "УЛ. ЕДЕЛВАЙС", onDemand: true },
  { name: "СЕЛО МИРОВЯНЕ", onDemand: true },
  { name: "УЛ. СПОРТИСТ", onDemand: true },
  { name: "МИРОВСКО ШОСЕ", onDemand: true },
  { name: "ОКОЛОВРЪСТЕН ПЪТ", onDemand: true },
  { name: "КВ. ТРЕБИЧ", onDemand: true },
  { name: "НАЧАЛО КВ. ТРЕБИЧ", onDemand: true },
  { name: "УЛ. ДЖЕРМАН", onDemand: false },
  { name: "УЛ. КИРИЛ БЛАГОЕВ", onDemand: false },
  { name: "ХЮНДАЙ БЪЛГАРИЯ", onDemand: false },
  { name: "СТОКОВ БАЗАР ИЛИЯНЦИ", onDemand: false },
  { name: "МОДНА КЪЩА АГРЕСИЯ", onDemand: false },
  { name: "ГАРА СОФИЯ СЕВЕР", onDemand: false }
]
            }
        ]
    },
	"bus-30": {
        number: "30",
        type: "bus",
        directions: [
            {
                name: "ОБЕЛЯ",
                stops: [
  { name: "СЕЛО БАЛША", onDemand: false },
  { name: "УЛ. СТАРА ПЛАНИНА", onDemand: false },
  { name: "ПО ЖЕЛАНИЕ", onDemand: true },
  { name: "КМЕТСТВО БАЛША", onDemand: false },
  { name: "МАНАСТИР СВ. ТЕОДОР СТРАТИЛАТ", onDemand: true },
  { name: "КРАЯ С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "ПЛ. МЕГДАНА", onDemand: false },
  { name: "НАЧАЛО С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "КРАЯ С. МРАМОР", onDemand: false },
  { name: "СЕЛО МРАМОР", onDemand: false },
  { name: "УЛ. ЗАХАРИ ЗОГРАФ", onDemand: false },
  { name: "НАЧАЛО С. МРАМОР", onDemand: true },
  { name: "ТИР ПАРКИНГ МРАМОР", onDemand: true },
  { name: "ПРОМИШЛЕНА ЗОНА УЛ. ВАСИЛ ЛЕВСКИ", onDemand: true },
  { name: "БЕТОНОВ ВЪЗЕЛ", onDemand: true },
  { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  { name: "УЛ. 2", onDemand: false },
  { name: "УЛ. 9", onDemand: false },
  { name: "КВ. ОБЕЛЯ", onDemand: false }
                ]
            },
            {
                name: "БАЛША",
                stops: [
  { name: "КВ. ОБЕЛЯ", onDemand: false },
  { name: "УЛ. 9", onDemand: false },
  { name: "УЛ. 2", onDemand: false },
  { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  { name: "БЕТОНОВ ВЪЗЕЛ", onDemand: true },
  { name: "ПРОМИШЛЕНА ЗОНА УЛ. ВАСИЛ ЛЕВСКИ", onDemand: true },
  { name: "ТИР ПАРКИНГ МРАМОР", onDemand: true },
  { name: "НАЧАЛО С. МРАМОР", onDemand: true },
  { name: "УЛ. ЗАХАРИ ЗОГРАФ", onDemand: false },
  { name: "СЕЛО МРАМОР", onDemand: false },
  { name: "КРАЯ С. МРАМОР", onDemand: false },
  { name: "НАЧАЛО С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "ПЛ. МЕГДАНА", onDemand: false },
  { name: "ПАМЕТНИКА С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "КРАЯ С. ДОБРОСЛАВЦИ", onDemand: false },
  { name: "МАНАСТИР СВ. ТЕОДОР СТРАТИЛАТ", onDemand: true },
  { name: "КМЕТСТВО БАЛША", onDemand: false },
  { name: "ПО ЖЕЛАНИЕ", onDemand: true },
  { name: "УЛ. СТАРА ПЛАНИНА", onDemand: false },
  { name: "СЕЛО БАЛША", onDemand: false }
]
            }
        ]
    },
	"bus-31": {
        number: "31",
        type: "bus",
        directions: [
            {
                name: "ОБЕЛЯ",
                stops: [
  { name: "СЕЛО ГОЛЯНОВЦИ", onDemand: false },
  { name: "НАЧАЛО С. ГОЛЯНОВЦИ", onDemand: false },
  { name: "КРАЯ С. ЖИТЕН", onDemand: false },
  { name: "СЕЛО ЖИТЕН", onDemand: false },
  { name: "УЛ. МИНЗУХАР", onDemand: false },
  { name: "НАЧАЛО С. ЖИТЕН", onDemand: false },
  { name: "БИОМЕТ ЕООД", onDemand: true },
  { name: "КРАЯ С. МРАМОР", onDemand: false },
  { name: "СЕЛО МРАМОР", onDemand: false },
  { name: "УЛ. ЗАХАРИ ЗОГРАФ", onDemand: false },
  { name: "НАЧАЛО С. МРАМОР", onDemand: true },
  { name: "ТИР ПАРКИНГ МРАМОР", onDemand: true },
  { name: "ПРОМИШЛЕНА ЗОНА УЛ. ВАСИЛ ЛЕВСКИ", onDemand: true },
  { name: "БЕТОНОВ ВЪЗЕЛ", onDemand: true },
  { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  { name: "УЛ. 2", onDemand: false },
  { name: "УЛ. 9", onDemand: false },
  { name: "КВ. ОБЕЛЯ", onDemand: false }
                ]
            },
            {
                name: "ГОЛЯНОВЦИ",
                stops: [
  { name: "КВ. ОБЕЛЯ", onDemand: false },
  { name: "УЛ. 9", onDemand: false },
  { name: "УЛ. 2", onDemand: false },
  { name: "МЕТРОСТАНЦИЯ ОБЕЛЯ", onDemand: false },
  { name: "Ж.К. ОБЕЛЯ-2", onDemand: false },
  { name: "БЕТОНОВ ВЪЗЕЛ", onDemand: true },
  { name: "ПРОМИШЛЕНА ЗОНА УЛ. ВАСИЛ ЛЕВСКИ", onDemand: true },
  { name: "ТИР ПАРКИНГ МРАМОР", onDemand: true },
  { name: "НАЧАЛО С. МРАМОР", onDemand: true },
  { name: "УЛ. ЗАХАРИ ЗОГРАФ", onDemand: false },
  { name: "СЕЛО МРАМОР", onDemand: false },
  { name: "КРАЯ С. МРАМОР", onDemand: false },
  { name: "БИОМЕТ ЕООД", onDemand: true },
  { name: "НАЧАЛО С. ЖИТЕН", onDemand: false },
  { name: "УЛ. МИНЗУХАР", onDemand: false },
  { name: "СЕЛО ЖИТЕН", onDemand: false },
  { name: "КРАЯ С. ЖИТЕН", onDemand: false },
  { name: "НАЧАЛО С. ГОЛЯНОВЦИ", onDemand: false },
  { name: "СЕЛО ГОЛЯНОВЦИ", onDemand: false }
]
            }
        ]
    },
};
